### ISSUE TITLE
Any plans for a specific license?

### ISSUE THREAD

**Issue by mr-eyes** [EBI-Metagenomics/mgnify-sourmash-component#5]
Hello,
I would like to use this project, but I couldn't find a license. Is there any plan to create one soon? Thanks!

**Comment by SandyRogers** [comment]
@mr-eyes thanks for your interest. It is currently licensed as ISC (specified in the `package.json`). We may relicense this as Apache v2 for consistency with many of our other projects, but at present it is ISC.

**Comment by mr-eyes** [comment]
Thanks for the prompt response!
